import { FormEvent, useEffect, useState } from "react"; import { Landmark, Plus, Wallet } from "lucide-react";
import { Modal } from "../components/Modal"; import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui"; import { money } from "../lib/format"; import { supabase } from "../lib/supabase"; import { useAuth } from "../state/AuthContext";
const labels:Record<string,string>={checking:"Conta corrente",savings:"Poupança",cash:"Dinheiro",wallet:"Carteira digital",investment:"Investimento",other:"Outra"};
export function AccountsPage(){const {membership}=useAuth();const [rows,setRows]=useState<any[]>([]);const [balances,setBalances]=useState<any[]>([]);const [open,setOpen]=useState(false);const [error,setError]=useState("");
 const refresh=async()=>{if(!membership)return;const [{data},{data:b}]=await Promise.all([supabase.from("financial_accounts").select("*").eq("group_id",membership.group_id).order("created_at"),supabase.rpc("get_account_balances",{p_group_id:membership.group_id})]);setRows(data??[]);setBalances(b??[])};
 useEffect(()=>{void refresh()},[membership]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!membership)return;const f=new FormData(e.currentTarget);const {error}=await supabase.from("financial_accounts").insert({group_id:membership.group_id,owner_member_id:membership.id,name:String(f.get("name")),institution:String(f.get("institution")||"")||null,account_type:String(f.get("type")),initial_balance:Number(f.get("balance")||0),include_in_available:f.get("available")==="on",color:String(f.get("color"))});if(error)return setError(error.message);setOpen(false);setError("");await refresh();}
 const total=balances.filter(x=>x.include_in_available).reduce((s,x)=>s+Number(x.balance),0);
 return <><PageHeader eyebrow="Onde seu dinheiro está" title="Contas financeiras" description="Contas bancárias, dinheiro, carteiras e investimentos sem misturar saldos." action={<button className="button primary" onClick={()=>setOpen(true)}><Plus/>Nova conta</button>}/><section className="summary-strip"><div><span>Disponível total</span><strong>{money.format(total)}</strong></div><small>Investimentos fora do disponível continuam visíveis no patrimônio.</small></section><div className="card-grid">{rows.length?rows.map(row=>{const b=balances.find(x=>x.id===row.id);return <article className="resource-card" key={row.id}><span className="resource-icon" style={{background:row.color}}>{row.account_type==="cash"?<Wallet/>:<Landmark/>}</span><div><small>{labels[row.account_type]}</small><h2>{row.name}</h2><p>{row.institution||"Conta manual"}</p></div><strong>{money.format(Number(b?.balance??row.initial_balance))}</strong><span className={row.include_in_available?"badge success":"badge"}>{row.include_in_available?"Disponível":"Patrimônio"}</span></article>}):<div className="panel span-all"><EmptyState icon={<Landmark/>} title="Cadastre onde seu dinheiro está" text="Comece por sua conta principal, poupança ou dinheiro em espécie."/></div>}</div>{open&&<Modal title="Nova conta financeira" description="Informe o saldo real na data de hoje." onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit}><label>Nome<input name="name" required placeholder="Ex.: Nubank"/></label><label>Instituição<input name="institution" placeholder="Banco ou instituição"/></label><div className="two-cols"><label>Tipo<select name="type">{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Saldo inicial<input name="balance" type="number" step=".01" defaultValue="0"/></label></div><label>Cor<input name="color" type="color" defaultValue="#0f7556"/></label><label className="check-row"><input name="available" type="checkbox" defaultChecked/>Incluir no saldo disponível</label>{error&&<ErrorMessage>{error}</ErrorMessage>}<button className="button primary">Salvar conta</button></form></Modal>}</>;
}
