import { FormEvent, useCallback, useEffect, useState } from "react";
import { Landmark, Pencil, Plus, Wallet } from "lucide-react";
import { Modal } from "../components/Modal";
import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui";
import { money } from "../lib/format";
import { supabase } from "../lib/supabase";
import { useAuth } from "../state/AuthContext";
const labels: Record<string, string> = { checking: "Conta corrente", savings: "Poupança", cash: "Dinheiro", wallet: "Carteira digital", investment: "Investimento", other: "Outra" };
export function AccountsPage() {
  const { membership } = useAuth(); const [rows, setRows] = useState<any[]>([]); const [balances, setBalances] = useState<any[]>([]); const [editing, setEditing] = useState<any | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const refresh = useCallback(async () => { if (!membership) return; const [{ data }, { data: b }] = await Promise.all([supabase.from("financial_accounts").select("*").eq("group_id", membership.group_id).order("created_at"), supabase.rpc("get_account_balances", { p_group_id: membership.group_id })]); setRows(data ?? []); setBalances(b ?? []); }, [membership]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!membership) return; const f = new FormData(e.currentTarget); const values = { name: String(f.get("name")), institution: String(f.get("institution") || "") || null, account_type: String(f.get("type")), initial_balance: Number(f.get("balance") || 0), include_in_available: f.get("available") === "on", color: String(f.get("color")), is_active: f.get("active") === "on" }; const result = editing ? await supabase.from("financial_accounts").update(values).eq("id", editing.id) : await supabase.from("financial_accounts").insert({ ...values, group_id: membership.group_id, owner_member_id: membership.id }); if (result.error) return setError(result.error.message); setOpen(false); setEditing(null); setError(""); await refresh(); }
  const total = balances.filter(x => x.include_in_available).reduce((s, x) => s + Number(x.balance), 0);
  return <><PageHeader eyebrow="Onde seu dinheiro está" title="Contas financeiras" description="Edite dados cadastrais; mudanças no saldo inicial são validadas pelo banco." action={<button className="button primary" onClick={() => { setEditing(null); setOpen(true); }}><Plus />Nova conta</button>} /><section className="summary-strip"><div><span>Disponível total</span><strong>{money.format(total)}</strong></div><small>Contas arquivadas preservam o histórico.</small></section><div className="card-grid">{rows.length ? rows.map(row => { const b = balances.find(x => x.id === row.id); return <article className="resource-card" key={row.id}><span className="resource-icon" style={{ background: row.color }}>{row.account_type === "cash" ? <Wallet /> : <Landmark />}</span><div><small>{labels[row.account_type]}</small><h2>{row.name}</h2><p>{row.institution || "Conta manual"}{!row.is_active && " • arquivada"}</p></div><strong>{money.format(Number(b?.balance ?? row.initial_balance))}</strong><div className="list-actions"><span className={row.include_in_available ? "badge success" : "badge"}>{row.include_in_available ? "Disponível" : "Patrimônio"}</span><button className="icon-action" title="Editar" onClick={() => { setEditing(row); setOpen(true); }}><Pencil /></button></div></article>; }) : <div className="panel span-all"><EmptyState icon={<Landmark />} title="Cadastre onde seu dinheiro está" text="Comece por sua conta principal, poupança ou dinheiro em espécie." /></div>}</div>{open && <Modal title={editing ? "Editar conta" : "Nova conta financeira"} description={editing ? "Se já houver movimentos, prefira um lançamento de ajuste para conciliação." : "Informe o saldo real na data de hoje."} onClose={() => { setOpen(false); setEditing(null); }}><form className="form-grid" onSubmit={submit}><label>Nome<input name="name" required defaultValue={editing?.name} /></label><label>Instituição<input name="institution" defaultValue={editing?.institution ?? ""} /></label><div className="two-cols"><label>Tipo<select name="type" defaultValue={editing?.account_type}>{Object.entries(labels).map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select></label><label>Saldo inicial<input name="balance" type="number" step=".01" defaultValue={editing?.initial_balance ?? 0} /></label></div><label>Cor<input name="color" type="color" defaultValue={editing?.color ?? "#0f7556"} /></label><label className="check-row"><input name="available" type="checkbox" defaultChecked={editing?.include_in_available ?? true} />Incluir no saldo disponível</label><label className="check-row"><input name="active" type="checkbox" defaultChecked={editing?.is_active ?? true} />Conta ativa</label>{error && <ErrorMessage>{error}</ErrorMessage>}<button className="button primary">Salvar conta</button></form></Modal>}</>;
}
