import { FormEvent, useCallback, useEffect, useState } from "react";
import { Archive, Pencil, Plus, Tags } from "lucide-react";
import { Modal } from "../components/Modal";
import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui";
import { supabase } from "../lib/supabase";
import { useAuth } from "../state/AuthContext";

export function CategoriesPage() {
  const { membership } = useAuth(); const [rows, setRows] = useState<any[]>([]); const [editing, setEditing] = useState<any | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState("");
  const refresh = useCallback(async () => { if (!membership) return; const { data } = await supabase.from("categories").select("*").or(`group_id.is.null,group_id.eq.${membership.group_id}`).order("kind").order("name"); setRows(data ?? []); }, [membership]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!membership) return; const f = new FormData(e.currentTarget); const values = { name: String(f.get("name")).trim(), kind: String(f.get("kind")), color: String(f.get("color")), icon: String(f.get("icon") || "tag"), is_active: true }; const result = editing ? await supabase.from("categories").update(values).eq("id", editing.id).eq("group_id", membership.group_id) : await supabase.from("categories").insert({ ...values, group_id: membership.group_id }); if (result.error) return setError(result.error.code === "23505" ? "Já existe uma categoria com esse nome e tipo." : result.error.message); setOpen(false); setEditing(null); setError(""); await refresh(); }
  async function archive(row: any) { if (!membership || !row.group_id) return; await supabase.from("categories").update({ is_active: !row.is_active }).eq("id", row.id).eq("group_id", membership.group_id); await refresh(); }
  return <><PageHeader eyebrow="Organização" title="Categorias" description="Use as categorias padrão ou crie classificações próprias para o grupo." action={<button className="button primary" onClick={() => { setEditing(null); setOpen(true); }}><Plus />Nova categoria</button>} />
    <div className="panel">{rows.length ? <div className="data-list">{rows.map(row => <article key={row.id}><span className="category-swatch" style={{ background: row.color ?? "#0f7556" }}><Tags /></span><div><strong>{row.name}</strong><small>{row.kind === "income" ? "Receita" : "Despesa"} • {row.group_id ? "Personalizada" : "Padrão StepFin"}{!row.is_active && " • arquivada"}</small></div>{row.group_id && <div className="list-actions"><button className="icon-action" title="Editar" onClick={() => { setEditing(row); setOpen(true); }}><Pencil /></button><button className="icon-action" title={row.is_active ? "Arquivar" : "Reativar"} onClick={() => void archive(row)}><Archive /></button></div>}</article>)}</div> : <EmptyState icon={<Tags />} title="Nenhuma categoria" text="Crie uma categoria para classificar seus movimentos." />}</div>
    {open && <Modal title={editing ? "Editar categoria" : "Nova categoria"} onClose={() => { setOpen(false); setEditing(null); }}><form className="form-grid" onSubmit={save}><label>Nome<input name="name" required defaultValue={editing?.name} /></label><div className="two-cols"><label>Tipo<select name="kind" defaultValue={editing?.kind ?? "expense"}><option value="expense">Despesa</option><option value="income">Receita</option></select></label><label>Cor<input name="color" type="color" defaultValue={editing?.color ?? "#0f7556"} /></label></div><label>Ícone<input name="icon" defaultValue={editing?.icon ?? "tag"} /></label>{error && <ErrorMessage>{error}</ErrorMessage>}<button className="button primary">Salvar</button></form></Modal>}</>;
}
