import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, PiggyBank, Receipt, Wallet } from "lucide-react";
import { Link } from "react-router-dom";
import { PageHeader } from "../components/Ui";
import { money } from "../lib/format"; import { supabase } from "../lib/supabase"; import { useAuth } from "../state/AuthContext";
type Dashboard={income?:number;expenses?:number;pending_bills?:number;caixinhas_balance?:number;expenses_by_category?:{category:string;total:number}[]};
export function DashboardPage(){const {membership}=useAuth();const [data,setData]=useState<Dashboard>({});const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!membership)return;supabase.rpc("get_group_dashboard",{group_id:membership.group_id,month:new Date().toISOString().slice(0,10)}).then(({data})=>{setData((data??{}) as Dashboard);setLoading(false);});},[membership]);
 const balance=(data.income??0)-(data.expenses??0);
 return <><PageHeader eyebrow="Resumo do mês" title="Sua vida financeira, em ordem." description="Acompanhe o que entrou, o que saiu e os próximos passos." action={<Link className="button primary" to="/transactions/new">+ Novo lançamento</Link>}/><section className="metric-grid"><article className="metric featured"><span><Wallet/>Saldo do mês</span><strong>{loading?"—":money.format(balance)}</strong><small className={balance>=0?"positive":"negative"}>{balance>=0?"Você está no caminho certo":"Revise seus gastos do mês"}</small></article><article className="metric"><span><ArrowUpRight/>Receitas</span><strong>{money.format(data.income??0)}</strong><small className="positive">Entradas no período</small></article><article className="metric"><span><ArrowDownRight/>Despesas</span><strong>{money.format(data.expenses??0)}</strong><small>Saídas no período</small></article><article className="metric"><span><PiggyBank/>Caixinhas</span><strong>{money.format(data.caixinhas_balance??0)}</strong><small>Reservas acumuladas</small></article></section><section className="dashboard-grid"><article className="panel"><div className="panel-title"><div><span className="eyebrow">Distribuição</span><h2>Gastos por categoria</h2></div></div>{data.expenses_by_category?.length?<div className="category-list">{data.expenses_by_category.map((x,i)=><div key={x.category}><span className="category-dot" style={{background:`hsl(${155+i*35} 55% 42%)`}}/><span>{x.category}</span><strong>{money.format(x.total)}</strong></div>)}</div>:<div className="mini-empty"><Receipt/><p>Seus gastos aparecerão aqui após o primeiro lançamento.</p></div>}</article><article className="panel next-step"><span className="eyebrow">Próximo passo</span><h2>Construa sua reserva</h2><p>Crie uma caixinha com objetivo e acompanhe sua evolução mensal.</p><Link to="/caixinhas">Ver caixinhas →</Link><div className="orb"/></article></section></>;
}
