import { FormEvent, useCallback, useEffect, useState } from "react";
import { Copy, Mail, Plus, Shield, UserMinus, Users, X } from "lucide-react";
import { Modal } from "../components/Modal";
import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui";
import { supabase } from "../lib/supabase";
import { useAuth } from "../state/AuthContext";
export function MembersPage() {
  const { membership } = useAuth(); const [members, setMembers] = useState<any[]>([]); const [invites, setInvites] = useState<any[]>([]); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  const refresh = useCallback(async () => { if (!membership) return; const [m, i] = await Promise.all([supabase.from("group_members").select("id,role,permission_level,user_id,profiles(full_name,email)").eq("group_id", membership.group_id).eq("is_active", true), supabase.from("group_invitations").select("*").eq("group_id", membership.group_id).eq("status", "pending")]); setMembers(m.data ?? []); setInvites(i.data ?? []); }, [membership]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function invite(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!membership) return; const f = new FormData(e.currentTarget); const { error } = await supabase.functions.invoke("send-invitation", { body: { groupId: membership.group_id, email: String(f.get("email")), permissionLevel: String(f.get("permission")), delivery: "link" } }); setMessage(error?.message ?? "Convite criado. Use Copiar link para enviá-lo pelo WhatsApp."); if (!error) { setOpen(false); await refresh(); } }
  async function permission(id: string, value: string) { const { error } = await supabase.from("group_members").update({ permission_level: value }).eq("id", id); if (error) setMessage(error.message); else await refresh(); }
  async function removeMember(id: string, name: string) { if (!confirm(`Remover o acesso de ${name}? O histórico financeiro será preservado.`)) return; const { error } = await supabase.rpc("remove_group_member", { p_member_id: id }); setMessage(error?.message ?? "Membro removido. O histórico foi preservado."); if (!error) await refresh(); }
  async function cancelInvite(id: string) { if (!confirm("Cancelar este convite pendente?")) return; const { error } = await supabase.rpc("cancel_group_invitation", { p_invitation_id: id }); setMessage(error?.message ?? "Convite cancelado."); if (!error) await refresh(); }
  async function copyInviteLink(invitation: any) { if (!membership) return; const { data, error } = await supabase.functions.invoke("send-invitation", { body: { groupId: membership.group_id, invitationId: invitation.id, delivery: "link" } }); if (error || !data?.inviteUrl) return setMessage(error?.message ?? "Não foi possível gerar o link."); try { await navigator.clipboard.writeText(data.inviteUrl); setMessage("Link copiado. Envie-o ao familiar pelo WhatsApp."); } catch { window.prompt("Copie o link do convite:", data.inviteUrl); } await refresh(); }
  return <><PageHeader eyebrow="Finanças compartilhadas" title="Membros" description="Convide sua família e ajuste permissões quando necessário." action={membership?.role === "owner" ? <button className="button primary" onClick={() => setOpen(true)}><Plus />Convidar</button> : undefined} /><div className="panel">{members.length ? <div className="data-list">{members.map(m => { const p = Array.isArray(m.profiles) ? m.profiles[0] : m.profiles; const name = p?.full_name || "Membro"; return <article key={m.id}><span className="avatar">{name.slice(0, 1).toUpperCase()}</span><div><strong>{name}</strong><small>{p?.email}</small></div>{membership?.role === "owner" && m.role !== "owner" ? <div className="list-actions"><select className="compact-select" value={m.permission_level} onChange={e => void permission(m.id, e.target.value)}><option value="read_write">Pode editar</option><option value="read_only">Somente leitura</option></select><button className="icon-action danger-icon" title="Remover membro" onClick={() => void removeMember(m.id, name)}><UserMinus /></button></div> : <span className="badge success"><Shield />Titular</span>}</article>; })}</div> : <EmptyState icon={<Users />} title="Somente você por enquanto" text="Convide alguém para cuidar das finanças em conjunto." />}</div>{invites.length > 0 && <section className="panel section-gap"><h2>Convites pendentes</h2><div className="data-list">{invites.map(i => <article key={i.id}><span className="transaction-icon income"><Mail /></span><div><strong>{i.invited_email}</strong><small>Expira em {new Date(i.expires_at).toLocaleDateString("pt-BR")}</small></div><div className="list-actions"><button className="mini-button" onClick={() => void copyInviteLink(i)}><Copy />Copiar link</button><button className="icon-action danger-icon" title="Cancelar convite" onClick={() => void cancelInvite(i.id)}><X /></button></div></article>)}</div></section>}{message && <div className="toast">{message}</div>}{open && <Modal title="Convidar membro" onClose={() => setOpen(false)}><form className="form-grid" onSubmit={invite}><label>E-mail<input name="email" type="email" required /></label><label>Permissão<select name="permission"><option value="read_write">Pode ver e editar</option><option value="read_only">Somente leitura</option></select></label><p className="form-note">O convite é válido por 7 dias, deve ser enviado manualmente e só pode ser aceito pelo e-mail informado.</p>{message && <ErrorMessage>{message}</ErrorMessage>}<button className="button primary">Criar convite</button></form></Modal>}</>;
}
