import { FormEvent, useEffect, useMemo, useState } from "react";import { ArrowRightLeft, Filter, Plus, ReceiptText } from "lucide-react";import { Link, useNavigate } from "react-router-dom";
import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui";import { loadFinanceOptions } from "../hooks/useFinanceData";import { money,shortDate } from "../lib/format";import { supabase } from "../lib/supabase";import { useAuth } from "../state/AuthContext";
export function TransactionsPage(){const {membership}=useAuth();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [filter,setFilter]=useState("all");
 useEffect(()=>{if(!membership)return;supabase.from("transactions").select("*,financial_accounts!transactions_account_id_fkey(name),cards(name),categories(name)").eq("group_id",membership.group_id).order("transaction_date",{ascending:false}).then(({data})=>{setRows(data??[]);setLoading(false)})},[membership]);
 const visible=useMemo(()=>rows.filter(r=>filter==="all"||r.kind===filter),[rows,filter]);
 return <><PageHeader eyebrow="Movimentações" title="Lançamentos" description="Receitas entram em contas; despesas saem de contas ou vão para o cartão." action={<Link className="button primary" to="/transactions/new"><Plus/>Novo lançamento</Link>}/><div className="toolbar"><Filter/><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Todos</button><button className={filter==="expense"?"active":""} onClick={()=>setFilter("expense")}>Despesas</button><button className={filter==="income"?"active":""} onClick={()=>setFilter("income")}>Receitas</button><button className={filter==="transfer"?"active":""} onClick={()=>setFilter("transfer")}>Transferências</button></div><div className="panel">{!loading&&!visible.length?<EmptyState icon={<ReceiptText/>} title="Nenhum lançamento" text="Registre uma receita, despesa ou transferência para começar." action={<Link className="button primary" to="/transactions/new">Registrar agora</Link>}/>:<div className="data-list">{visible.map(row=><article key={row.id}><div className={`transaction-icon ${row.kind}`}>{row.kind==="income"?"↑":row.kind==="transfer"?<ArrowRightLeft/>:"↓"}</div><div><strong>{row.description}</strong><small>{shortDate(row.transaction_date)} • {row.cards?.name??row.financial_accounts?.name??row.payment_method??"sem conta"}{row.categories?.name&&` • ${row.categories.name}`}</small></div><strong className={row.kind==="income"?"positive":row.kind==="expense"?"negative":""}>{row.kind==="income"?"+ ":row.kind==="expense"?"− ":""}{money.format(row.amount)}</strong></article>)}</div>}</div></>;
}
export function NewTransactionPage(){const {membership}=useAuth();const nav=useNavigate();const [kind,setKind]=useState<"expense"|"income"|"transfer">("expense");const [method,setMethod]=useState("pix");const [options,setOptions]=useState<any>({accounts:[],cards:[],categories:[]});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{if(membership)loadFinanceOptions(membership.group_id).then(setOptions)},[membership]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!membership)return;setBusy(true);const f=new FormData(e.currentTarget);const account=String(f.get("account")||"")||null;const destination=String(f.get("destination")||"")||null;const card=String(f.get("card")||"")||null;const payload:any={group_id:membership.group_id,member_id:membership.id,description:String(f.get("description")),amount:Number(f.get("amount")),transaction_date:String(f.get("date")),kind,entry_method:"manual",status:String(f.get("status")),category_id:String(f.get("category")||"")||null,notes:String(f.get("notes")||"")||null,payment_method:kind==="transfer"?"transfer":kind==="income"?"transfer":method,account_id:kind==="transfer"||kind==="income"?account:(method==="credit"?null:account),destination_account_id:kind==="transfer"?destination:null,card_id:kind==="expense"&&method==="credit"?card:null};
  if(kind==="income"&&!account)return setError("Selecione a conta que receberá a receita"),setBusy(false);if(kind==="expense"&&method==="credit"&&!card)return setError("Selecione o cartão"),setBusy(false);if(kind==="expense"&&method!=="credit"&&!account)return setError("Selecione a conta de origem"),setBusy(false);if(kind==="transfer"&&(!account||!destination||account===destination))return setError("Selecione contas diferentes para a transferência"),setBusy(false);
  const {error}=await supabase.from("transactions").insert(payload);if(error){setError(error.message);setBusy(false)}else nav("/transactions");
 }
 const categories=options.categories.filter((x:any)=>x.kind===(kind==="income"?"income":"expense"));
 return <div className="narrow"><PageHeader eyebrow="Novo lançamento" title="Registre o movimento completo" description="A origem e o destino mantêm seus saldos coerentes."/><form className="panel form-grid" onSubmit={submit}><div className="segmented three"><button type="button" className={kind==="expense"?"active":""} onClick={()=>setKind("expense")}>Despesa</button><button type="button" className={kind==="income"?"active":""} onClick={()=>setKind("income")}>Receita</button><button type="button" className={kind==="transfer"?"active":""} onClick={()=>setKind("transfer")}>Transferência</button></div><label>Descrição<input name="description" required placeholder={kind==="income"?"Ex.: Salário":kind==="transfer"?"Ex.: Reserva mensal":"Ex.: Supermercado"}/></label><div className="two-cols"><label>Valor<input name="amount" type="number" min=".01" step=".01" required/></label><label>Data<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label></div>{kind!=="transfer"&&<label>Categoria<select name="category"><option value="">Sem categoria</option>{categories.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}{kind==="expense"&&<label>Meio de pagamento<select value={method} onChange={e=>setMethod(e.target.value)}><option value="pix">Pix</option><option value="debit">Débito</option><option value="credit">Crédito</option><option value="cash">Dinheiro</option><option value="bank_slip">Boleto</option><option value="other">Outro</option></select></label>}<label>{kind==="income"?"Conta de destino":kind==="transfer"?"Conta de origem":method==="credit"?"Cartão":"Conta de origem"}{method==="credit"&&kind==="expense"?<select name="card" required><option value="">Selecione</option>{options.cards.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select>:<select name="account" required><option value="">Selecione</option>{options.accounts.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select>}</label>{kind==="transfer"&&<label>Conta de destino<select name="destination" required><option value="">Selecione</option>{options.accounts.map((x:any)=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<label>Status<select name="status"><option value="cleared">{kind==="income"?"Recebida":kind==="expense"?"Paga":"Concluída"}</option><option value="pending">Pendente</option><option value="scheduled">Prevista</option></select></label><label>Observações<textarea name="notes"/></label>{error&&<ErrorMessage>{error}</ErrorMessage>}<div className="form-actions"><button className="button ghost" type="button" onClick={()=>nav(-1)}>Cancelar</button><button className="button primary" disabled={busy}>{busy?"Salvando…":"Salvar lançamento"}</button></div></form></div>;
}
