import { FormEvent, useEffect, useState } from "react"; import { Plus, ReceiptText } from "lucide-react"; import { Link, useNavigate } from "react-router-dom";
import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui"; import { money,shortDate } from "../lib/format"; import { supabase } from "../lib/supabase"; import { useAuth } from "../state/AuthContext"; import type { Tables } from "../types/database";
export function TransactionsPage(){const {membership}=useAuth();const [rows,setRows]=useState<Tables<"transactions">[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!membership)return;supabase.from("transactions").select("*").eq("group_id",membership.group_id).order("transaction_date",{ascending:false}).then(({data})=>{setRows(data??[]);setLoading(false);});},[membership]);
 return <><PageHeader eyebrow="Movimentações" title="Lançamentos" description="Tudo que entra e sai, sem perder nenhum detalhe." action={<Link className="button primary" to="/transactions/new"><Plus/>Novo lançamento</Link>}/><div className="panel">{!loading&&!rows.length?<EmptyState icon={<ReceiptText/>} title="Nenhum lançamento ainda" text="Registre uma receita ou despesa para começar." action={<Link className="button primary" to="/transactions/new">Registrar agora</Link>}/>:<div className="data-list">{rows.map(row=><article key={row.id}><div className={`transaction-icon ${row.kind}`}>{row.kind==="income"?"↑":"↓"}</div><div><strong>{row.description}</strong><small>{shortDate(row.transaction_date)} • {row.entry_method}</small></div><strong className={row.kind==="income"?"positive":""}>{row.kind==="income"?"+ ":"− "}{money.format(row.amount)}</strong></article>)}</div>}</div></>;
}
export function NewTransactionPage(){const {membership}=useAuth();const nav=useNavigate();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!membership)return;setBusy(true);const form=new FormData(e.currentTarget);const {error}=await supabase.from("transactions").insert({group_id:membership.group_id,member_id:membership.id,description:String(form.get("description")),amount:Number(form.get("amount")),transaction_date:String(form.get("date")),kind:String(form.get("kind")),entry_method:"manual"});if(error){setError(error.message);setBusy(false);}else nav("/transactions");}
 return <div className="narrow"><PageHeader eyebrow="Novo lançamento" title="Registre em poucos segundos" description="Revise os dados antes de salvar."/><form className="panel form-grid" onSubmit={submit}><label>Descrição<input name="description" required placeholder="Ex.: Supermercado"/></label><div className="two-cols"><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required placeholder="0,00"/></label><label>Data<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label></div><label>Tipo<select name="kind"><option value="expense">Despesa</option><option value="income">Receita</option></select></label>{error&&<ErrorMessage>{error}</ErrorMessage>}<div className="form-actions"><button className="button ghost" type="button" onClick={()=>nav(-1)}>Cancelar</button><button className="button primary" disabled={busy}>{busy?"Salvando…":"Salvar lançamento"}</button></div></form></div>;
}
