import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ArrowRightLeft, Paperclip, Pencil, Plus, ReceiptText } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { Modal } from "../components/Modal";
import { EmptyState, ErrorMessage, PageHeader } from "../components/Ui";
import { money, shortDate } from "../lib/format";
import { supabase } from "../lib/supabase";
import { useAuth } from "../state/AuthContext";
import { loadFinanceOptions } from "../hooks/useFinanceData";

const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => today().slice(0, 8) + "01";

export function TransactionsPage() {
  const { membership } = useAuth(); const [rows, setRows] = useState<any[]>([]); const [options, setOptions] = useState<any>({ accounts: [], cards: [], categories: [] }); const [editing, setEditing] = useState<any | null>(null); const [error, setError] = useState("");
  const [filters, setFilters] = useState({ from: monthStart(), to: today(), kind: "all", account: "", category: "", status: "", search: "" });
  const refresh = useCallback(async () => { if (!membership) return; let query = supabase.from("transactions").select("*,financial_accounts!transactions_account_id_fkey(name),cards(name),categories(name)").eq("group_id", membership.group_id).order("transaction_date", { ascending: false }); if (filters.from) query = query.gte("transaction_date", filters.from); if (filters.to) query = query.lte("transaction_date", filters.to); if (filters.kind !== "all") query = query.eq("kind", filters.kind); if (filters.account) query = query.or(`account_id.eq.${filters.account},destination_account_id.eq.${filters.account}`); if (filters.category) query = query.eq("category_id", filters.category); if (filters.status) query = query.eq("status", filters.status); if (filters.search) query = query.ilike("description", `%${filters.search}%`); const [{ data, error }, o] = await Promise.all([query, loadFinanceOptions(membership.group_id)]); setRows(data ?? []); setOptions(o); setError(error?.message ?? ""); }, [membership, filters]);
  useEffect(() => { void refresh(); }, [refresh]);
  async function saveEdit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!editing) return; const f = new FormData(e.currentTarget); const { error } = await supabase.from("transactions").update({ description: String(f.get("description")), amount: Number(f.get("amount")), transaction_date: String(f.get("date")), category_id: String(f.get("category") || "") || null, status: String(f.get("status")), notes: String(f.get("notes") || "") || null }).eq("id", editing.id); if (error) return setError(error.message); setEditing(null); await refresh(); }
  return <><PageHeader eyebrow="Movimentações" title="Lançamentos" description="Consulte por período, conta e categoria; alterações ficam registradas no histórico." action={<Link className="button primary" to="/transactions/new"><Plus />Novo lançamento</Link>} />
    <section className="panel filter-panel"><div className="filter-grid"><label>De<input type="date" value={filters.from} onChange={e => setFilters({ ...filters, from: e.target.value })} /></label><label>Até<input type="date" value={filters.to} onChange={e => setFilters({ ...filters, to: e.target.value })} /></label><label>Tipo<select value={filters.kind} onChange={e => setFilters({ ...filters, kind: e.target.value })}><option value="all">Todos</option><option value="expense">Despesas</option><option value="income">Receitas</option><option value="transfer">Transferências</option><option value="card_payment">Pagamentos de fatura</option></select></label><label>Conta<select value={filters.account} onChange={e => setFilters({ ...filters, account: e.target.value })}><option value="">Todas</option>{options.accounts.map((x: any) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Categoria<select value={filters.category} onChange={e => setFilters({ ...filters, category: e.target.value })}><option value="">Todas</option>{options.categories.map((x: any) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Status<select value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="">Todos</option><option value="cleared">Efetivado</option><option value="pending">Pendente</option><option value="scheduled">Previsto</option><option value="cancelled">Cancelado</option></select></label><label className="search-field">Buscar<input value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} placeholder="Descrição" /></label></div></section>
    <div className="panel">{!rows.length ? <EmptyState icon={<ReceiptText />} title="Nenhum lançamento no período" text="Altere os filtros ou registre um novo movimento." /> : <div className="data-list">{rows.map(row => <article key={row.id}><div className={`transaction-icon ${row.kind}`}>{row.kind === "income" ? "↑" : row.kind === "transfer" ? <ArrowRightLeft /> : "↓"}</div><div><strong>{row.description}</strong><small>{shortDate(row.transaction_date)} • {row.cards?.name ?? row.financial_accounts?.name ?? row.payment_method ?? "sem conta"}{row.categories?.name && ` • ${row.categories.name}`}</small></div><div className="list-actions">{row.receipt_file_path && <ReceiptPreview path={row.receipt_file_path} />}<strong className={row.kind === "income" ? "positive" : row.kind === "expense" ? "negative" : ""}>{row.kind === "income" ? "+ " : row.kind === "expense" ? "− " : ""}{money.format(row.amount)}</strong><button className="icon-action" title="Editar" onClick={() => setEditing(row)}><Pencil /></button></div></article>)}</div>}</div>
    {editing && <Modal title="Editar lançamento" description="O saldo será revalidado antes de salvar." onClose={() => setEditing(null)}><form className="form-grid" onSubmit={saveEdit}><label>Descrição<input name="description" defaultValue={editing.description} required /></label><div className="two-cols"><label>Valor<input name="amount" type="number" min=".01" step=".01" defaultValue={editing.amount} required /></label><label>Data<input name="date" type="date" defaultValue={editing.transaction_date} required /></label></div><label>Categoria<select name="category" defaultValue={editing.category_id ?? ""}><option value="">Sem categoria</option>{options.categories.filter((x: any) => x.is_active !== false).map((x: any) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Status<select name="status" defaultValue={editing.status}><option value="cleared">Efetivado</option><option value="pending">Pendente</option><option value="scheduled">Previsto</option><option value="cancelled">Cancelado</option></select></label><label>Observações<textarea name="notes" defaultValue={editing.notes ?? ""} /></label>{error && <ErrorMessage>{error}</ErrorMessage>}<button className="button primary">Salvar alteração</button></form></Modal>}</>;
}

function ReceiptPreview({ path }: { path: string }) { const [url, setUrl] = useState(""); async function open() { if (!url) { const { data } = await supabase.storage.from("receipts").createSignedUrl(path, 60); setUrl(data?.signedUrl ?? ""); } } return <a className="receipt-preview" href={url || undefined} target="_blank" rel="noreferrer" onMouseEnter={() => void open()} onFocus={() => void open()} onClick={e => { if (!url) { e.preventDefault(); void open(); } }}><Paperclip />{url && /\.(png|jpe?g|webp)$/i.test(path) && <img src={url} alt="Comprovante" />}</a>; }

export function NewTransactionPage() {
  const { membership } = useAuth(); const nav = useNavigate(); const [kind, setKind] = useState("expense"); const [method, setMethod] = useState("pix"); const [options, setOptions] = useState<any>({ accounts: [], cards: [], categories: [] }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (membership) void loadFinanceOptions(membership.group_id).then(setOptions); }, [membership]);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!membership) return; setBusy(true); const f = new FormData(e.currentTarget); const account = String(f.get("account") || "") || null; const destination = String(f.get("destination") || "") || null; const card = String(f.get("card") || "") || null; const payload: any = { group_id: membership.group_id, member_id: membership.id, description: String(f.get("description")), amount: Number(f.get("amount")), transaction_date: String(f.get("date")), kind, entry_method: "manual", status: String(f.get("status")), category_id: String(f.get("category") || "") || null, notes: String(f.get("notes") || "") || null, payment_method: kind === "transfer" || kind === "income" ? "transfer" : method, account_id: kind === "transfer" || kind === "income" ? account : method === "credit" ? null : account, destination_account_id: kind === "transfer" ? destination : null, card_id: kind === "expense" && method === "credit" ? card : null }; const { error } = await supabase.from("transactions").insert(payload); if (error) { setError(error.message); setBusy(false); } else nav("/transactions"); }
  const categories = useMemo(() => options.categories.filter((x: any) => x.is_active !== false && x.kind === (kind === "income" ? "income" : "expense")), [options, kind]);
  return <div className="narrow"><PageHeader eyebrow="Novo lançamento" title="Registre o movimento completo" description="Despesas e transferências são recusadas se a conta não tiver saldo." /><form className="panel form-grid" onSubmit={submit}><div className="segmented three"><button type="button" className={kind === "expense" ? "active" : ""} onClick={() => setKind("expense")}>Despesa</button><button type="button" className={kind === "income" ? "active" : ""} onClick={() => setKind("income")}>Receita</button><button type="button" className={kind === "transfer" ? "active" : ""} onClick={() => setKind("transfer")}>Transferência</button></div><label>Descrição<input name="description" required /></label><div className="two-cols"><label>Valor<input name="amount" type="number" min=".01" step=".01" required /></label><label>Data<input name="date" type="date" required defaultValue={today()} /></label></div>{kind !== "transfer" && <label>Categoria<select name="category"><option value="">Sem categoria</option>{categories.map((x: any) => <option value={x.id} key={x.id}>{x.name}</option>)}</select><Link className="field-link" to="/categories">+ Criar categoria</Link></label>}{kind === "expense" && <label>Meio de pagamento<select value={method} onChange={e => setMethod(e.target.value)}><option value="pix">Pix</option><option value="debit">Débito</option><option value="credit">Crédito</option><option value="cash">Dinheiro</option><option value="bank_slip">Boleto</option><option value="other">Outro</option></select></label>}<label>{kind === "income" ? "Conta de destino" : kind === "transfer" ? "Conta de origem" : method === "credit" ? "Cartão" : "Conta de origem"}{method === "credit" && kind === "expense" ? <select name="card" required><option value="">Selecione</option>{options.cards.map((x: any) => <option value={x.id} key={x.id}>{x.name}</option>)}</select> : <select name="account" required><option value="">Selecione</option>{options.accounts.map((x: any) => <option value={x.id} key={x.id}>{x.name}</option>)}</select>}</label>{kind === "transfer" && <label>Conta de destino<select name="destination" required><option value="">Selecione</option>{options.accounts.map((x: any) => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<label>Status<select name="status"><option value="cleared">Efetivado</option><option value="pending">Pendente</option><option value="scheduled">Previsto</option></select></label><label>Observações<textarea name="notes" /></label>{error && <ErrorMessage>{error}</ErrorMessage>}<div className="form-actions"><button className="button ghost" type="button" onClick={() => nav(-1)}>Cancelar</button><button className="button primary" disabled={busy}>{busy ? "Salvando…" : "Salvar lançamento"}</button></div></form></div>;
}
